import type { ComponentType } from "react";
import type { Locale } from "./locales";

/**
 * Explicit (locale, slug) -> MDX loader map. Static literal import() calls are
 * required for Turbopack static export. Every locale has all files (untranslated
 * ones start as English copies). Keep in sync with the manifest + locales.
 */
type MdxLoader = () => Promise<{ default: ComponentType }>;

export const LEARN_CONTENT: Record<Locale, Record<string, MdxLoader>> = {
  en: {
    "understanding-your-health-metrics": () => import("./en/understanding-your-health-metrics.mdx"),
    "resting-heart-rate": () => import("./en/resting-heart-rate.mdx"),
    "heart-rate-variability": () => import("./en/heart-rate-variability.mdx"),
    "reading-your-blood-pressure": () => import("./en/reading-your-blood-pressure.mdx"),
    "your-ecg-recordings": () => import("./en/your-ecg-recordings.mdx"),
    "sleep-consistency": () => import("./en/sleep-consistency.mdx"),
    "respiratory-rate": () => import("./en/respiratory-rate.mdx"),
    "blood-oxygen-spo2": () => import("./en/blood-oxygen-spo2.mdx"),
    "body-temperature-baseline": () => import("./en/body-temperature-baseline.mdx"),
    "blood-sugar-beyond-diabetes": () => import("./en/blood-sugar-beyond-diabetes.mdx"),
    "vo2max-and-longevity": () => import("./en/vo2max-and-longevity.mdx"),
    "beyond-the-scale": () => import("./en/beyond-the-scale.mdx"),
    "tracking-mood": () => import("./en/tracking-mood.mdx"),
    "the-cycle-as-a-vital-sign": () => import("./en/the-cycle-as-a-vital-sign.mdx"),
    "how-wearables-measure-you": () => import("./en/how-wearables-measure-you.mdx"),
    "reading-your-trends": () => import("./en/reading-your-trends.mdx"),
    "steps-and-movement": () => import("./en/steps-and-movement.mdx"),
    "caffeine-alcohol-and-your-readings": () => import("./en/caffeine-alcohol-and-your-readings.mdx"),
    "hydration-and-your-body": () => import("./en/hydration-and-your-body.mdx"),
    "stress-and-recovery": () => import("./en/stress-and-recovery.mdx"),
    "screening-not-diagnosis": () => import("./en/screening-not-diagnosis.mdx"),
    "longevity-labs-explained": () => import("./en/longevity-labs-explained.mdx"),
    "waist-and-central-fat": () => import("./en/waist-and-central-fat.mdx"),
    "grip-strength-as-a-vital-sign": () => import("./en/grip-strength-as-a-vital-sign.mdx"),
    "weather-altitude-and-your-body": () => import("./en/weather-altitude-and-your-body.mdx"),
  },
  de: {
    "understanding-your-health-metrics": () => import("./de/understanding-your-health-metrics.mdx"),
    "resting-heart-rate": () => import("./de/resting-heart-rate.mdx"),
    "heart-rate-variability": () => import("./de/heart-rate-variability.mdx"),
    "reading-your-blood-pressure": () => import("./de/reading-your-blood-pressure.mdx"),
    "your-ecg-recordings": () => import("./de/your-ecg-recordings.mdx"),
    "sleep-consistency": () => import("./de/sleep-consistency.mdx"),
    "respiratory-rate": () => import("./de/respiratory-rate.mdx"),
    "blood-oxygen-spo2": () => import("./de/blood-oxygen-spo2.mdx"),
    "body-temperature-baseline": () => import("./de/body-temperature-baseline.mdx"),
    "blood-sugar-beyond-diabetes": () => import("./de/blood-sugar-beyond-diabetes.mdx"),
    "vo2max-and-longevity": () => import("./de/vo2max-and-longevity.mdx"),
    "beyond-the-scale": () => import("./de/beyond-the-scale.mdx"),
    "tracking-mood": () => import("./de/tracking-mood.mdx"),
    "the-cycle-as-a-vital-sign": () => import("./de/the-cycle-as-a-vital-sign.mdx"),
    "how-wearables-measure-you": () => import("./de/how-wearables-measure-you.mdx"),
    "reading-your-trends": () => import("./de/reading-your-trends.mdx"),
    "steps-and-movement": () => import("./de/steps-and-movement.mdx"),
    "caffeine-alcohol-and-your-readings": () => import("./de/caffeine-alcohol-and-your-readings.mdx"),
    "hydration-and-your-body": () => import("./de/hydration-and-your-body.mdx"),
    "stress-and-recovery": () => import("./de/stress-and-recovery.mdx"),
    "screening-not-diagnosis": () => import("./de/screening-not-diagnosis.mdx"),
    "longevity-labs-explained": () => import("./de/longevity-labs-explained.mdx"),
    "waist-and-central-fat": () => import("./de/waist-and-central-fat.mdx"),
    "grip-strength-as-a-vital-sign": () => import("./de/grip-strength-as-a-vital-sign.mdx"),
    "weather-altitude-and-your-body": () => import("./de/weather-altitude-and-your-body.mdx"),
  },
  es: {
    "understanding-your-health-metrics": () => import("./es/understanding-your-health-metrics.mdx"),
    "resting-heart-rate": () => import("./es/resting-heart-rate.mdx"),
    "heart-rate-variability": () => import("./es/heart-rate-variability.mdx"),
    "reading-your-blood-pressure": () => import("./es/reading-your-blood-pressure.mdx"),
    "your-ecg-recordings": () => import("./es/your-ecg-recordings.mdx"),
    "sleep-consistency": () => import("./es/sleep-consistency.mdx"),
    "respiratory-rate": () => import("./es/respiratory-rate.mdx"),
    "blood-oxygen-spo2": () => import("./es/blood-oxygen-spo2.mdx"),
    "body-temperature-baseline": () => import("./es/body-temperature-baseline.mdx"),
    "blood-sugar-beyond-diabetes": () => import("./es/blood-sugar-beyond-diabetes.mdx"),
    "vo2max-and-longevity": () => import("./es/vo2max-and-longevity.mdx"),
    "beyond-the-scale": () => import("./es/beyond-the-scale.mdx"),
    "tracking-mood": () => import("./es/tracking-mood.mdx"),
    "the-cycle-as-a-vital-sign": () => import("./es/the-cycle-as-a-vital-sign.mdx"),
    "how-wearables-measure-you": () => import("./es/how-wearables-measure-you.mdx"),
    "reading-your-trends": () => import("./es/reading-your-trends.mdx"),
    "steps-and-movement": () => import("./es/steps-and-movement.mdx"),
    "caffeine-alcohol-and-your-readings": () => import("./es/caffeine-alcohol-and-your-readings.mdx"),
    "hydration-and-your-body": () => import("./es/hydration-and-your-body.mdx"),
    "stress-and-recovery": () => import("./es/stress-and-recovery.mdx"),
    "screening-not-diagnosis": () => import("./es/screening-not-diagnosis.mdx"),
    "longevity-labs-explained": () => import("./es/longevity-labs-explained.mdx"),
    "waist-and-central-fat": () => import("./es/waist-and-central-fat.mdx"),
    "grip-strength-as-a-vital-sign": () => import("./es/grip-strength-as-a-vital-sign.mdx"),
    "weather-altitude-and-your-body": () => import("./es/weather-altitude-and-your-body.mdx"),
  },
  fr: {
    "understanding-your-health-metrics": () => import("./fr/understanding-your-health-metrics.mdx"),
    "resting-heart-rate": () => import("./fr/resting-heart-rate.mdx"),
    "heart-rate-variability": () => import("./fr/heart-rate-variability.mdx"),
    "reading-your-blood-pressure": () => import("./fr/reading-your-blood-pressure.mdx"),
    "your-ecg-recordings": () => import("./fr/your-ecg-recordings.mdx"),
    "sleep-consistency": () => import("./fr/sleep-consistency.mdx"),
    "respiratory-rate": () => import("./fr/respiratory-rate.mdx"),
    "blood-oxygen-spo2": () => import("./fr/blood-oxygen-spo2.mdx"),
    "body-temperature-baseline": () => import("./fr/body-temperature-baseline.mdx"),
    "blood-sugar-beyond-diabetes": () => import("./fr/blood-sugar-beyond-diabetes.mdx"),
    "vo2max-and-longevity": () => import("./fr/vo2max-and-longevity.mdx"),
    "beyond-the-scale": () => import("./fr/beyond-the-scale.mdx"),
    "tracking-mood": () => import("./fr/tracking-mood.mdx"),
    "the-cycle-as-a-vital-sign": () => import("./fr/the-cycle-as-a-vital-sign.mdx"),
    "how-wearables-measure-you": () => import("./fr/how-wearables-measure-you.mdx"),
    "reading-your-trends": () => import("./fr/reading-your-trends.mdx"),
    "steps-and-movement": () => import("./fr/steps-and-movement.mdx"),
    "caffeine-alcohol-and-your-readings": () => import("./fr/caffeine-alcohol-and-your-readings.mdx"),
    "hydration-and-your-body": () => import("./fr/hydration-and-your-body.mdx"),
    "stress-and-recovery": () => import("./fr/stress-and-recovery.mdx"),
    "screening-not-diagnosis": () => import("./fr/screening-not-diagnosis.mdx"),
    "longevity-labs-explained": () => import("./fr/longevity-labs-explained.mdx"),
    "waist-and-central-fat": () => import("./fr/waist-and-central-fat.mdx"),
    "grip-strength-as-a-vital-sign": () => import("./fr/grip-strength-as-a-vital-sign.mdx"),
    "weather-altitude-and-your-body": () => import("./fr/weather-altitude-and-your-body.mdx"),
  },
  it: {
    "understanding-your-health-metrics": () => import("./it/understanding-your-health-metrics.mdx"),
    "resting-heart-rate": () => import("./it/resting-heart-rate.mdx"),
    "heart-rate-variability": () => import("./it/heart-rate-variability.mdx"),
    "reading-your-blood-pressure": () => import("./it/reading-your-blood-pressure.mdx"),
    "your-ecg-recordings": () => import("./it/your-ecg-recordings.mdx"),
    "sleep-consistency": () => import("./it/sleep-consistency.mdx"),
    "respiratory-rate": () => import("./it/respiratory-rate.mdx"),
    "blood-oxygen-spo2": () => import("./it/blood-oxygen-spo2.mdx"),
    "body-temperature-baseline": () => import("./it/body-temperature-baseline.mdx"),
    "blood-sugar-beyond-diabetes": () => import("./it/blood-sugar-beyond-diabetes.mdx"),
    "vo2max-and-longevity": () => import("./it/vo2max-and-longevity.mdx"),
    "beyond-the-scale": () => import("./it/beyond-the-scale.mdx"),
    "tracking-mood": () => import("./it/tracking-mood.mdx"),
    "the-cycle-as-a-vital-sign": () => import("./it/the-cycle-as-a-vital-sign.mdx"),
    "how-wearables-measure-you": () => import("./it/how-wearables-measure-you.mdx"),
    "reading-your-trends": () => import("./it/reading-your-trends.mdx"),
    "steps-and-movement": () => import("./it/steps-and-movement.mdx"),
    "caffeine-alcohol-and-your-readings": () => import("./it/caffeine-alcohol-and-your-readings.mdx"),
    "hydration-and-your-body": () => import("./it/hydration-and-your-body.mdx"),
    "stress-and-recovery": () => import("./it/stress-and-recovery.mdx"),
    "screening-not-diagnosis": () => import("./it/screening-not-diagnosis.mdx"),
    "longevity-labs-explained": () => import("./it/longevity-labs-explained.mdx"),
    "waist-and-central-fat": () => import("./it/waist-and-central-fat.mdx"),
    "grip-strength-as-a-vital-sign": () => import("./it/grip-strength-as-a-vital-sign.mdx"),
    "weather-altitude-and-your-body": () => import("./it/weather-altitude-and-your-body.mdx"),
  },
  pl: {
    "understanding-your-health-metrics": () => import("./pl/understanding-your-health-metrics.mdx"),
    "resting-heart-rate": () => import("./pl/resting-heart-rate.mdx"),
    "heart-rate-variability": () => import("./pl/heart-rate-variability.mdx"),
    "reading-your-blood-pressure": () => import("./pl/reading-your-blood-pressure.mdx"),
    "your-ecg-recordings": () => import("./pl/your-ecg-recordings.mdx"),
    "sleep-consistency": () => import("./pl/sleep-consistency.mdx"),
    "respiratory-rate": () => import("./pl/respiratory-rate.mdx"),
    "blood-oxygen-spo2": () => import("./pl/blood-oxygen-spo2.mdx"),
    "body-temperature-baseline": () => import("./pl/body-temperature-baseline.mdx"),
    "blood-sugar-beyond-diabetes": () => import("./pl/blood-sugar-beyond-diabetes.mdx"),
    "vo2max-and-longevity": () => import("./pl/vo2max-and-longevity.mdx"),
    "beyond-the-scale": () => import("./pl/beyond-the-scale.mdx"),
    "tracking-mood": () => import("./pl/tracking-mood.mdx"),
    "the-cycle-as-a-vital-sign": () => import("./pl/the-cycle-as-a-vital-sign.mdx"),
    "how-wearables-measure-you": () => import("./pl/how-wearables-measure-you.mdx"),
    "reading-your-trends": () => import("./pl/reading-your-trends.mdx"),
    "steps-and-movement": () => import("./pl/steps-and-movement.mdx"),
    "caffeine-alcohol-and-your-readings": () => import("./pl/caffeine-alcohol-and-your-readings.mdx"),
    "hydration-and-your-body": () => import("./pl/hydration-and-your-body.mdx"),
    "stress-and-recovery": () => import("./pl/stress-and-recovery.mdx"),
    "screening-not-diagnosis": () => import("./pl/screening-not-diagnosis.mdx"),
    "longevity-labs-explained": () => import("./pl/longevity-labs-explained.mdx"),
    "waist-and-central-fat": () => import("./pl/waist-and-central-fat.mdx"),
    "grip-strength-as-a-vital-sign": () => import("./pl/grip-strength-as-a-vital-sign.mdx"),
    "weather-altitude-and-your-body": () => import("./pl/weather-altitude-and-your-body.mdx"),
  },
};

